Presentation/LojaProduto.Presentation/Controllers/Pedido/PedidoController.cs
using LojaProduto.Presentation.Controllers.Base;
using LojaProduto.Services.Spec.DataTransferObjects;
using LojaProduto.Presentation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace LojaProduto.Presentation.Controllers.Pedido
{
    public class PedidoController : CustomController
    {
        // GET: Pedido
        public ActionResult Pedido(int idProduto = 0, int quantidadeProduto = 0)
        {
            var pedido = GetCadastroService().ObtemPedidoEmAberto(CodigoCliente);     
            
            if (pedido == null)
            {
                pedido = GetCadastroService().CriaPedido(CodigoCliente);
            }

            GetCadastroService().AdicionaItemPedido(pedido.Id, quantidadeProduto, idProduto);

            return Json(JsonRequestBehavior.DenyGet);
        }

        public ActionResult Pedidos()
        {
            Pedidos model = new Pedidos();

            var resultado = GetCadastroService().ListarItensPedidos();
            model.ItensPedidos = resultado.ToList();            

            return View(model);
        }
    }
}

Presentation/LojaProduto.Presentation/Controllers/Produto/ProdutoController.cs
using LojaProduto.Presentation.Controllers.Base;
using LojaProduto.Presentation.Models;
using LojaProduto.Services.Spec.DataTransferObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaProduto.Presentation.Controllers
{
    public class ProdutoController : CustomController
    {
        // GET: Produto
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Form()
        {
            return View();
        }

        public ActionResult ListaProdutos(string query)
        {
            ListaProdutos model = new ListaProdutos();

            model.TextoDePesquisa = query;
            if (query != null)
            {
                var result = GetCadastroService().PesquisarProdutos(query);
                model.Produtos = result.ToList();

                return View(model);
            }
            else
            {
                var result = GetCadastroService().ListarProdutos();
                model.Produtos = result.ToList();

                return View(model);// Json(result, JsonRequestBehavior.DenyGet);   
            }
        }

        public ActionResult CadastrarProduto(DTOProduto produto)
        {
            if (ModelState.IsValid)
            {
                produto = GetCadastroService().SalvarProduto(produto);

                return InformationMessage("Informação", "O registro foi gravado com sucesso.", Url.Action("Index"));
            }
            else
                return ErrorMessage("Erro", "Registro Inválido!");
        }

        //public ActionResult PesquisarProdutos(string query)
        //{
        //    var produto = GetCadastroService().PesquisarProdutos(query);

        //    ListaProdutos model = new ListaProdutos();

        //    //var result = GetCadastroService().ListarProdutos();
        //    //model.Produtos = result.ToList();
        //    return View();
        //}

    }
}

Presentation/LojaProduto.Presentation/Views/Shared/_Layout.cshtml
@using LojaProduto.Presentation.Helpers;
@using MvcSiteMapProvider.Web.Html;

<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[if IE 7]> <html class="ie7" lang="@System.Threading.Thread.CurrentThread.CurrentCulture" xmlns="http://www.w3.org/1999/xhtml"> <![endif]-->
<!--[if IE 8]> <html class="ie8" lang="@System.Threading.Thread.CurrentThread.CurrentCulture" xmlns="http://www.w3.org/1999/xhtml"> <![endif]-->
<!--[if IE 9]> <html class="ie9" lang="@System.Threading.Thread.CurrentThread.CurrentCulture" xmlns="http://www.w3.org/1999/xhtml"> <![endif]-->
<!--[if gt IE 9]><!-->
<html lang="@System.Threading.Thread.CurrentThread.CurrentCulture" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Produto</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="Wings4Cloud - Squadra Tecnologia" />
    <title>LojaProduto - @ViewBag.Title</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
    @Styles.Render("~/Theme/css")
    @Styles.Render("~/Content/jqueryui")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    @*<div id="form1">*@
    <header class="header" ?=?>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Loja Produtos de Limpeza</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Produtos", "ListaProdutos", "Produto")</li>
                        <li>@Html.ActionLink("Pedidos", "Pedidos", "Pedido")</li>
                        <li>@Html.ActionLink("Categoria", "Index", "Categoria")</li>
                        <li><a href="#">Clientes</a></li>
                        <li><a href="#">Fornecedores</a></li>
                        <li>@Html.ActionLink("Cadastros", "Form", "Produto")</li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="content">
        <div id="Corpo">
            @RenderBody()
        </div>
        <footer></footer>
    </div>
    @*</div>*@
    <div id="loading" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="divModalLabel" aria-hidden="true" data-backdrop="false">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    &nbsp;
                </div>
                <div class="modal-body text-center">
                    <img src="@Url.Content("~/App_Themes/Default/images/ajax-loader.gif")" />
                    Processando...
                </div>
                <div class="modal-footer">
                </div>
            </div>   
        </div>
    </div>
     
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryplugin")
    @Scripts.Render("~/bundles/jqueryajax")
    @Scripts.Render("~/bundles/jquery-js-utils")

    @RenderSection("scripts", required: false)
    @RenderSection("bottomLevel", false)

    <script type="text/javascript">
        DataHoraExtenso('DataHoraAtual');
        setInterval("DataHoraExtenso('DataHoraAtual');", 1000);

        $(document).ready(function () {
            Globalize.culture('@System.Threading.Thread.CurrentThread.CurrentCulture');
        });
    </script>
</body>
</html>

Presentation/LojaProduto.Presentation/Views/Shared/_Pagination.cshtml
@model SQFramework.Data.Pagging.PageMessage

@{
    int pageCount = (int)Math.Ceiling((decimal)Model.RowsCount / Model.PageSize);
    int previousPage = Model.ActualPage - 1;
    int nextPage = Model.ActualPage + 1;
    int pageRadius = 10;
    int startPage = (Model.ActualPage - pageRadius / 2);

    if ((startPage + pageRadius - 1) > pageCount)
    {
        startPage = pageCount - pageRadius + 1;
    }

    startPage = (startPage < 1 ? 1 : startPage);

    int endPage = (startPage + pageRadius - 1);

    if (endPage > pageCount)
    {
        endPage = pageCount;
    }

    var indexes = new List<int>();
    for (var i = startPage; i <= endPage; i++)
    {
        indexes.Add(i);
    }
    <nav class="text-center">
        <ul class="pagination">
            <li><span class="glyphicon">@Model.ActualPage de @pageCount</span></li>
            @if (previousPage < 1)
            {
                <li class="disabled"><span class="glyphicon glyphicon-step-backward btn btn-link"></span></li>
                <li class="disabled"><span class="glyphicon glyphicon-chevron-left btn btn-link"></span></li>
            }
            else
            {
                <li><span class="ui-table-control-next glyphicon glyphicon-step-backward btn btn-link" data-columns-page="1"></span></li>
                <li><span class="ui-table-control-next glyphicon glyphicon-chevron-left btn btn-link" data-columns-page="@previousPage"></span></li>
            }
            @foreach (var item in indexes)
            {
                if (item == Model.ActualPage)
                {
                    <li class="active"><span class="ui-table-control-next glyphicon btn btn-link" data-columns-page="@item">@item</span></li>
                }
                else
                {
                    <li><span class="ui-table-control-next glyphicon btn btn-link" data-columns-page="@item">@item</span></li>
                }
            }
            @if (nextPage > pageCount)
            {
                <li class="disabled"><span class="glyphicon glyphicon-chevron-right btn btn-link"></span></li>
                <li class="disabled"><span class="glyphicon glyphicon-step-forward btn btn-link"></span></li>
            }
            else
            {
                <li><span class="ui-table-control-next glyphicon glyphicon-chevron-right btn btn-link" data-columns-page="@nextPage"></span></li>
                <li><span class="ui-table-control-next glyphicon glyphicon-step-forward btn btn-link" data-columns-page="@pageCount"></span></li>
            }
        </ul>
    </nav>
}

Presentation/LojaProduto.Presentation/Views/Shared/_Portal.cshtml
@using LojaProduto.Presentation.Helpers;

@if (Request.IsAuthenticated)
{
    <ul class="nav navbar-nav navbar-right">
        <li class="inactive">
            @Html.ConfirmationLink("Portal Sistemas", "PortalSistemas", "Home", "Portal de Sistemas", "Deseja realmente sair para o portal de sistemas?")
        </li>
        <li>
            @Html.ConfirmationLink("Sair", "Logoff", "Home", "Sair", "Deseja terminar a sessão?")
        </li>
    </ul>
}

Presentation/LojaProduto.Presentation/Views/Shared/_UserInfo.cshtml
@using SCA.WebControls

@if (Request.IsAuthenticated && SCAApplicationContext.Usuario != null)
{
    <span class="nome-user">Bem - vindo(a) @SCAApplicationContext.Usuario.Nome</span>
}
else
{
    <span class="nome-user">&nbsp;</span>
}